=== scottalger/primefaces/src/main/resources-maven-jsf/misc/component.dtd
<!ELEMENT component (tag,tagClass,componentClass,componentHandlerClass?,componentType,componentFamily,rendererType?,rendererClass?,parent,interfaces?,attributes,resources*)>
<!ELEMENT tagman (#PCDATA)>
<!ELEMENT tagClass (#PCDATA)>
<!ELEMENT componentClass (#PCDATA)>
<!ELEMENT componentHandlerClass (#PCDATA)>
<!ELEMENT componentType (#PCDATA)>
<!ELEMENT componentFamily (#PCDATA)>
<!ELEMENT rendererType (#PCDATA)>
<!ELEMENT rendererClass (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT interfaces (interface)>
<!ELEMENT interface (name)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (name,required,type,method-signature?,ignoreInComponent?,defaultValue?,description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT method-signature (#PCDATA)>
<!ELEMENT ignoreInComponent (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT resources (resource*)>
<!ELEMENT resource (name)>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/contextMenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>contextMenu</tag>
	<tagClass>org.primefaces.component.contextmenu.ContextMenuTag</tagClass>
	<componentClass>org.primefaces.component.contextmenu.ContextMenu</componentClass>
	<componentType>org.primefaces.component.ContextMenu</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.ContextMenuRenderer</rendererType>
	<rendererClass>org.primefaces.component.contextmenu.ContextMenuRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>for</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>zindex</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>java.lang.Integer.MAX_VALUE</defaultValue>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>menu/menu.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>yui/utilities/utilities.js</name>
		</resource>
        <resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>menu/menu.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/hotkey.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
    <tag>hotkey</tag>
    <tagClass>org.primefaces.component.hotkey.HotkeyTag</tagClass>
    <componentClass>org.primefaces.component.hotkey.Hotkey</componentClass>
    <componentType>org.primefaces.component.Hotkey</componentType>
    <componentFamily>org.primefaces.component</componentFamily>
    <rendererType>org.primefaces.component.HotkeyRenderer</rendererType>
    <rendererClass>org.primefaces.component.hotkey.HotkeyRenderer</rendererClass>
    <parent>javax.faces.component.UICommand</parent>
    <interfaces>
        <interface>
            <name>org.primefaces.component.api.AjaxSource</name>
        </interface>
    </interfaces>
    <attributes>
        &standard_uicomponent_attributes;
        <attribute>
            <name>actionListener</name>
            <required>false</required>
            <type>javax.faces.event.ActionListener</type>
            <method-signature>void actionListener(javax.faces.event.ActionEvent)</method-signature>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>action</name>
            <required>false</required>
            <type>javax.el.MethodExpression</type>
            <method-signature>java.lang.Object action()</method-signature>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>immediate</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>bind</name>
            <required>true</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>update</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>process</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>handler</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>onstart</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>oncomplete</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>onerror</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>onsuccess</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>global</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
        </attribute>
        <attribute>
            <name>async</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
        </attribute>
    </attributes>
    <resources>
        <resource>
            <name>jquery/jquery.js</name>
        </resource>
        <resource>
            <name>hotkey/jquery.hotkeys.js</name>
        </resource>
        <resource>
            <name>core/core.js</name>
        </resource>
    </resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/columnGroup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>columnGroup</tag>
	<tagClass>org.primefaces.component.columngroup.ColumnGroupTag</tagClass>
	<componentClass>org.primefaces.component.columngroup.ColumnGroup</componentClass>
	<componentType>org.primefaces.component.ColumnGroup</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
        <attribute>
			<name>type</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Location of the columnGroup, valid values are header or footer.</description>
		</attribute>
	</attributes>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/columns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
    <tag>columns</tag>
    <tagClass>org.primefaces.component.columns.ColumnsTag</tagClass>
    <componentClass>org.primefaces.component.columns.Columns</componentClass>
    <componentType>org.primefaces.component.Columns</componentType>
    <componentFamily>org.primefaces.component</componentFamily>
    <parent>javax.faces.component.UIColumn</parent>
    <attributes>
		&standard_uicomponent_attributes;
        <attribute>
            <name>value</name>
            <required>false</required>
            <type>java.lang.Object</type>
            <description>
                Value referring to a collection of columns.
            </description>
        </attribute>
        <attribute>
            <name>var</name>
            <required>true</required>
            <type>java.lang.String</type>
            <description>
                Name of the request-scoped variable that'll be used as the holder of each column.
            </description>
        </attribute>
        <attribute>
            <name>columnIndexVar</name>
            <required>true</required>
            <type>java.lang.String</type>
            <description>
                Name of the request-scoped variable that'll be used as the holder of each column index.
            </description>
        </attribute>
    </attributes>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/divider.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>divider</tag>
	<tagClass>org.primefaces.component.divider.DividerTag</tagClass>
	<componentClass>org.primefaces.component.divider.Divider</componentClass>
	<componentType>org.primefaces.component.Divider</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
    <rendererType>org.primefaces.component.DividerRenderer</rendererType>
	<rendererClass>org.primefaces.component.divider.DividerRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
         <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description></description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description></description>
        </attribute>
        <attribute>
            <name>type</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>dotted</defaultValue>
            <description></description>
        </attribute>
	</attributes>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/pickList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>pickList</tag>
	<tagClass>org.primefaces.component.picklist.PickListTag</tagClass>
	<componentClass>org.primefaces.component.picklist.PickList</componentClass>
	<componentType>org.primefaces.component.PickList</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.PickListRenderer</rendererType>
	<rendererClass>org.primefaces.component.picklist.PickListRenderer</rendererClass>
	<parent>javax.faces.component.UIInput</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&input_component_attributes;
		&widget_var_attribute;
		<attribute>
			<name>var</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>itemLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>itemValue</name>
			<required>false</required>
			<type>java.lang.Object</type>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>disabled</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
		</attribute>
        <attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>fade</defaultValue>
		</attribute>
        <attribute>
			<name>effectSpeed</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>fast</defaultValue>
		</attribute>
        <attribute>
			<name>iconOnly</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
		</attribute>
        <attribute>
			<name>addLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Add</defaultValue>
		</attribute>
        <attribute>
			<name>addAllLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Add All</defaultValue>
		</attribute>
        <attribute>
			<name>removeLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Remove</defaultValue>
		</attribute>
        <attribute>
			<name>removeAllLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Remove All</defaultValue>
		</attribute>
        <attribute>
			<name>moveUpLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Move Up</defaultValue>
		</attribute>
        <attribute>
			<name>moveTopLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Move Top</defaultValue>
		</attribute>
        <attribute>
			<name>moveDownLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Move Down</defaultValue>
		</attribute>
        <attribute>
			<name>moveBottomLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Move Bottom</defaultValue>
		</attribute>
        <attribute>
			<name>showSourceControls</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
		</attribute>
        <attribute>
			<name>showTargetControls</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
		</attribute>
        <attribute>
			<name>onTransfer</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>picklist/picklist.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>jquery/jquery-ui.js</name>
		</resource>
		<resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>picklist/picklist.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/resource.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>resource</tag>
	<tagClass>org.primefaces.component.resource.ResourceTag</tagClass>
	<componentClass>org.primefaces.component.resource.Resource</componentClass>
	<componentType>org.primefaces.component.Resource</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.ResourceRenderer</rendererType>
	<rendererClass>org.primefaces.component.resource.ResourceRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_ui_component_attributes;
		<attribute>
			<name>name</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
	</attributes>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/commandButton.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY command_component_attributes			SYSTEM "../entities/command_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
<!ENTITY html_command_button_attributes			SYSTEM "../entities/html_command_button_attributes.xml">
]>
<component>
	<tag>commandButton</tag>
	<tagClass>org.primefaces.component.commandbutton.CommandButtonTag</tagClass>
	<componentClass>org.primefaces.component.commandbutton.CommandButton</componentClass>
	<componentType>org.primefaces.component.CommandButton</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.CommandButtonRenderer</rendererType>
	<rendererClass>org.primefaces.component.commandbutton.CommandButtonRenderer</rendererClass>
	<parent>javax.faces.component.html.HtmlCommandButton</parent>
	<interfaces>
		<interface>
			<name>org.primefaces.component.api.AjaxSource</name>
		</interface>
        <interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&command_component_attributes;
		&widget_var_attribute;
		<attribute>
			<name>ajax</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
		</attribute>
		<attribute>
			<name>async</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
		</attribute>
		<attribute>
			<name>process</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>update</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>onstart</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>oncomplete</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>onerror</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>onsuccess</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>global</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
		</attribute>
		<attribute>
			<name>accesskey</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>alt</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>dir</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>disabled</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>image</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>label</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>lang</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>tabindex</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>type</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>readonly</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onblur</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onchange</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onclick</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>ondblclick</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onfocus</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onkeydown</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onkeypress</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onkeyup</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onmousedown</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onmousemove</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onmouseout</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onmouseover</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onmouseup</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>onselect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>jquery/ui/jquery-ui.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>jquery/ui/jquery-ui.js</name>
		</resource>
		<resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>button/button.js</name>
		</resource>
	</resources>
</component>
