=== scottalger/primefaces/src/main/resources-maven-jsf/misc/component.dtd
<!ELEMENT component (tag,tagClass,componentClass,componentHandlerClass?,componentType,componentFamily,rendererType?,rendererClass?,parent,interfaces?,attributes,resources*)>
<!ELEMENT tagman (#PCDATA)>
<!ELEMENT tagClass (#PCDATA)>
<!ELEMENT componentClass (#PCDATA)>
<!ELEMENT componentHandlerClass (#PCDATA)>
<!ELEMENT componentType (#PCDATA)>
<!ELEMENT componentFamily (#PCDATA)>
<!ELEMENT rendererType (#PCDATA)>
<!ELEMENT rendererClass (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT interfaces (interface)>
<!ELEMENT interface (name)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (name,required,type,method-signature?,ignoreInComponent?,defaultValue?,description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT method-signature (#PCDATA)>
<!ELEMENT ignoreInComponent (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT resources (resource*)>
<!ELEMENT resource (name)>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/separator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>separator</tag>
	<tagClass>org.primefaces.component.separator.SeparatorTag</tagClass>
	<componentClass>org.primefaces.component.separator.Separator</componentClass>
	<componentType>org.primefaces.component.Separator</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.SeparatorRenderer</rendererType>
	<rendererClass>org.primefaces.component.separator.SeparatorRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
	</attributes>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/imageCropper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>imageCropper</tag>
	<tagClass>org.primefaces.component.imagecropper.ImageCropperTag</tagClass>
	<componentClass>org.primefaces.component.imagecropper.ImageCropper</componentClass>
	<componentType>org.primefaces.component.ImageCropper</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.ImageCropperRenderer</rendererType>
	<rendererClass>org.primefaces.component.imagecropper.ImageCropperRenderer</rendererClass>
	<parent>javax.faces.component.UIInput</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&input_component_attributes;
		&widget_var_attribute;
		<attribute>
			<name>image</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>alt</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>aspectRatio</name>
			<required>false</required>
			<type>java.lang.Double</type>
            <defaultValue>java.lang.Double.MIN_VALUE</defaultValue>
		</attribute>
        <attribute>
			<name>minSize</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>maxSize</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>backgroundColor</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>backgroundOpacity</name>
			<required>false</required>
			<type>java.lang.Double</type>
            <defaultValue>0.6</defaultValue>
		</attribute>
        <attribute>
			<name>initialCoords</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>imagecropper/imagecropper.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>imagecropper/imagecropper.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/headerRow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>headerRow</tag>
	<tagClass>org.primefaces.component.headerrow.HeaderRowTag</tagClass>
	<componentClass>org.primefaces.component.headerrow.HeaderRow</componentClass>
	<componentType>org.primefaces.component.HeaderRow</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
	</attributes>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/checkButton.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes             SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>checkButton</tag>
	<tagClass>org.primefaces.component.checkbutton.CheckButtonTag</tagClass>
	<componentClass>org.primefaces.component.checkbutton.CheckButton</componentClass>
	<componentType>org.primefaces.component.CheckButton</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.CheckButtonRenderer</rendererType>
	<rendererClass>org.primefaces.component.checkbutton.CheckButtonRenderer</rendererClass>
	<parent>javax.faces.component.UIInput</parent>
	<interfaces>
        <interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&input_component_attributes;
		&widget_var_attribute;
        <attribute>
			<name>label</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>
				Label of the button when checked
			</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>jquery/ui/jquery-ui.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>jquery/ui/jquery-ui.js</name>
		</resource>
		<resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>button/button.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/accordionPanel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>accordionPanel</tag>
	<tagClass>org.primefaces.component.accordionpanel.AccordionPanelTag</tagClass>
	<componentClass>org.primefaces.component.accordionpanel.AccordionPanel</componentClass>
    <componentHandlerClass>org.primefaces.component.accordionpanel.AccordionPanelHandler</componentHandlerClass>
	<componentType>org.primefaces.component.AccordionPanel</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.AccordionPanelRenderer</rendererType>
	<rendererClass>org.primefaces.component.accordionpanel.AccordionPanelRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>activeIndex</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>0</defaultValue>
			<description>Index of the active tab.</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style of the root container of accordion panel</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style class of the root container of accordion panel</description>
		</attribute>
		<attribute>
			<name>disabled</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Disables or enables accordion</description>
		</attribute>
		<attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>slide</defaultValue>
			<description>Effect to use when toggling the content</description>
		</attribute>
		<attribute>
			<name>autoHeight</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
			<description>When enabled, highest content is used as the reference. Provides more consistent animations.</description>
		</attribute>
		<attribute>
			<name>collapsible</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>Defines if accordion can be collapsed all together.</description>
		</attribute>
		<attribute>
			<name>fillSpace</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
			<description>When enabled, accordion fills the height of it's parent.</description>
		</attribute>
		<attribute>
			<name>event</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Specifies the event to use to toggle a tab.</description>
		</attribute>
        <attribute>
            <name>tabChangeListener</name>
            <required>false</required>
            <type>javax.el.MethodExpression</type>
            <method-signature>void tabChangeListener(org.primefaces.event.TabChangeEvent)</method-signature>
            <description>Server side listener to invoke when a tab has changed.</description>
        </attribute>
        <attribute>
            <name>onTabChangeUpdate</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Component(s) to update after tabChangeListener is invoked.</description>
        </attribute>
        <attribute>
            <name>onTabChange</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to invoke when active tab changes.</description>
        </attribute>
        <attribute>
            <name>dynamic</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Specifies the toggleMode, dynamic setting fetches it's content with ajax on tab switch.</description>
        </attribute>
        <attribute>
            <name>cache</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>When tab contents are lazy loaded by ajax toggleMode, caching only retrieves the tab contents once and subsequent toggles of a cached tab
			does not communicate with server. If caching is turned off, tab contents are refetched from server each time tab is clicked. This setting is true by default.
            </description>
        </attribute>
	</attributes>
	<resources>
		<resource>
			<name>jquery/ui/jquery-ui.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>jquery/ui/jquery-ui.js</name>
		</resource>	
		<resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>accordion/accordion.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/notificationBar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>notificationBar</tag>
	<tagClass>org.primefaces.component.notificationbar.NotificationBarTag</tagClass>
	<componentClass>org.primefaces.component.notificationbar.NotificationBar</componentClass>
	<componentType>org.primefaces.component.NotificationBar</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.NotificationBarRenderer</rendererType>
	<rendererClass>org.primefaces.component.notificationbar.NotificationBarRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>position</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>top</defaultValue>
		</attribute>
		<attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>fade</defaultValue>
		</attribute>
		<attribute>
			<name>effectSpeed</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>normal</defaultValue>
		</attribute>
		<attribute>
			<name>autoDisplay</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>notificationbar/notificationbar.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>notificationbar/notificationbar.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>resources</tag>
	<tagClass>org.primefaces.component.resources.ResourcesTag</tagClass>
	<componentClass>org.primefaces.component.resources.Resources</componentClass>
	<componentType>org.primefaces.component.Resources</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.ResourcesRenderer</rendererType>
	<rendererClass>org.primefaces.component.resources.ResourcesRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_ui_component_attributes;
		<attribute>
			<name>exclude</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Comma seperated list of resources to exclude.</description>
		</attribute>
	</attributes>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/remoteCommand.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY command_component_attributes			SYSTEM "../entities/command_component_attributes.xml">
]>
<component>
    <tag>remoteCommand</tag>
    <tagClass>org.primefaces.component.remotecommand.RemoteCommandTag</tagClass>
    <componentClass>org.primefaces.component.remotecommand.RemoteCommand</componentClass>
    <componentType>org.primefaces.component.RemoteCommand</componentType>
    <componentFamily>org.primefaces.component</componentFamily>
    <rendererType>org.primefaces.component.RemoteCommandRenderer</rendererType>
    <rendererClass>org.primefaces.component.remotecommand.RemoteCommandRenderer</rendererClass>
    <parent>javax.faces.component.UICommand</parent>
    <interfaces>
        <interface>
            <name>org.primefaces.component.api.AjaxSource</name>
        </interface>
    </interfaces>
    <attributes>
        &command_component_attributes;
        <attribute>
            <name>name</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>update</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>process</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>onstart</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>oncomplete</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>onerror</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>onsuccess</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>global</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
        </attribute>
        <attribute>
            <name>async</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
        </attribute>
    </attributes>
    <resources>
        <resource>
            <name>jquery/jquery.js</name>
        </resource>
        <resource>
            <name>core/core.js</name>
        </resource>
    </resources>
</component>
