=== scottalger/primefaces/src/main/resources-maven-jsf/misc/component.dtd
<!ELEMENT component (tag,tagClass,componentClass,componentHandlerClass?,componentType,componentFamily,rendererType?,rendererClass?,parent,interfaces?,attributes,resources*)>
<!ELEMENT tagman (#PCDATA)>
<!ELEMENT tagClass (#PCDATA)>
<!ELEMENT componentClass (#PCDATA)>
<!ELEMENT componentHandlerClass (#PCDATA)>
<!ELEMENT componentType (#PCDATA)>
<!ELEMENT componentFamily (#PCDATA)>
<!ELEMENT rendererType (#PCDATA)>
<!ELEMENT rendererClass (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT interfaces (interface)>
<!ELEMENT interface (name)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (name,required,type,method-signature?,ignoreInComponent?,defaultValue?,description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT method-signature (#PCDATA)>
<!ELEMENT ignoreInComponent (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT resources (resource*)>
<!ELEMENT resource (name)>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/spacer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>spacer</tag>
	<tagClass>org.primefaces.component.spacer.SpacerTag</tagClass>
	<componentClass>org.primefaces.component.spacer.Spacer</componentClass>
	<componentType>org.primefaces.component.Spacer</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.SpacerRenderer</rendererType>
	<rendererClass>org.primefaces.component.spacer.SpacerRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>width</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description></description>
		</attribute>
		<attribute>
			<name>height</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description></description>
		</attribute>
        <attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description></description>
		</attribute>
        <attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description></description>
		</attribute>
        <attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description></description>
		</attribute>
	</attributes>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/imageSwitch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>imageSwitch</tag>
	<tagClass>org.primefaces.component.imageswitch.ImageSwitchTag</tagClass>
	<componentClass>org.primefaces.component.imageswitch.ImageSwitch</componentClass>
	<componentType>org.primefaces.component.ImageSwitch</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.ImageSwitchRenderer</rendererType>
	<rendererClass>org.primefaces.component.imageswitch.ImageSwitchRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>effect</name>
			<required>true</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>speed</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>500</defaultValue>
		</attribute>
		<attribute>
			<name>slideshowSpeed</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>3000</defaultValue>
		</attribute>
		<attribute>
			<name>slideshowAuto</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>imageswitch/imageswitch.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/ajaxStatus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>ajaxStatus</tag>
	<tagClass>org.primefaces.component.ajaxstatus.AjaxStatusTag</tagClass>
	<componentClass>org.primefaces.component.ajaxstatus.AjaxStatus</componentClass>
	<componentType>org.primefaces.component.AjaxStatus</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.AjaxStatusRenderer</rendererType>
	<rendererClass>org.primefaces.component.ajaxstatus.AjaxStatusRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>onstart</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>oncomplete</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>onprestart</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>onsuccess</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>onerror</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>ajaxstatus/ajaxstatus.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/wizard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
    <tag>wizard</tag>
    <tagClass>org.primefaces.component.wizard.WizardTag</tagClass>
    <componentClass>org.primefaces.component.wizard.Wizard</componentClass>
    <componentHandlerClass>org.primefaces.component.wizard.WizardHandler</componentHandlerClass>
    <componentType>org.primefaces.component.Wizard</componentType>
    <componentFamily>org.primefaces.component</componentFamily>
    <rendererType>org.primefaces.component.WizardRenderer</rendererType>
    <rendererClass>org.primefaces.component.wizard.WizardRenderer</rendererClass>
    <parent>javax.faces.component.UIComponentBase</parent>
     <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
    <attributes>
        &standard_uicomponent_attributes;
        &widget_var_attribute;
        <attribute>
            <name>step</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>flowListener</name>
            <required>false</required>
            <type>javax.el.MethodExpression</type>
            <method-signature>void flowListener()</method-signature>
        </attribute>
        <attribute>
            <name>showNavBar</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
        </attribute>
        <attribute>
            <name>onback</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>onnext</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>nextLabel</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>Next</defaultValue>
        </attribute>
        <attribute>
            <name>backLabel</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>Back</defaultValue>
        </attribute>
        <attribute>
            <name>effect</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
        </attribute>
        <attribute>
            <name>effectSpeed</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>normal</defaultValue>
        </attribute>
    </attributes>
    <resources>
        <resource>
            <name>wizard/wizard.css</name>
        </resource>
        <resource>
			<name>jquery/ui/jquery-ui.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>jquery/ui/jquery-ui.js</name>
		</resource>
        <resource>
            <name>core/core.js</name>
        </resource>
        <resource>
            <name>wizard/wizard.js</name>
        </resource>
    </resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/spreadsheet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>spreadsheet</tag>
	<tagClass>org.primefaces.component.spreadsheet.SpreadsheetTag</tagClass>
	<componentClass>org.primefaces.component.spreadsheet.Spreadsheet</componentClass>
	<componentType>org.primefaces.component.Spreadsheet</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.SpreadsheetRenderer</rendererType>
	<rendererClass>org.primefaces.component.spreadsheet.SpreadsheetRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
     <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>editable</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
		</attribute>
		<attribute>
			<name>columnWidth</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>java.lang.Integer.MIN_VALUE</defaultValue>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>sheet/sheet.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>jquery/ui/jquery-ui.js</name>
		</resource>
        <resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>sheet/sheet.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/button.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>button</tag>
	<tagClass>org.primefaces.component.button.ButtonTag</tagClass>
	<componentClass>org.primefaces.component.button.Button</componentClass>
	<componentType>org.primefaces.component.Button</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.ButtonRenderer</rendererType>
	<rendererClass>org.primefaces.component.button.ButtonRenderer</rendererClass>
	<parent>javax.faces.component.html.HtmlOutcomeTargetButton</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>fragment</name>
			<type>java.lang.String</type>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>jquery/ui/jquery-ui.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>jquery/ui/jquery-ui.js</name>
		</resource>
		<resource>
			<name>core/core.js</name>
		</resource>
		<resource>
			<name>button/button.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/focus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>focus</tag>
	<tagClass>org.primefaces.component.focus.FocusTag</tagClass>
	<componentClass>org.primefaces.component.focus.Focus</componentClass>
	<componentType>org.primefaces.component.Focus</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.FocusRenderer</rendererType>
	<rendererClass>org.primefaces.component.focus.FocusRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>for</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>context</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>minSeverity</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>error</defaultValue>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>core/core.js</name>
		</resource>
	</resources>
</component>

=== scottalger/primefaces/src/main/resources-maven-jsf/ui/tabview.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
    <tag>tabView</tag>
    <tagClass>org.primefaces.component.tabview.TabViewTag</tagClass>
    <componentClass>org.primefaces.component.tabview.TabView</componentClass>
    <componentHandlerClass>org.primefaces.component.tabview.TabViewHandler</componentHandlerClass>
    <componentType>org.primefaces.component.TabView</componentType>
    <componentFamily>org.primefaces.component</componentFamily>
    <rendererType>org.primefaces.component.TabViewRenderer</rendererType>
    <rendererClass>org.primefaces.component.tabview.TabViewRenderer</rendererClass>
    <parent>javax.faces.component.UIComponentBase</parent>
     <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
    <attributes>
        &standard_uicomponent_attributes;
        &widget_var_attribute;
        <attribute>
            <name>activeIndex</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>0</defaultValue>
            <description>Index of the active tab</description>
        </attribute>
        <attribute>
            <name>effect</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Applies a transition effect during changing the tabs. Valid values are 'opacity', 'height' and 'width'.</description>
        </attribute>
        <attribute>
            <name>effectDuration</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>normal</defaultValue>
            <description>Defines the duration of effect</description>
        </attribute>
        <attribute>
            <name>dynamic</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Specifies the toggleMode, dynamic setting fetches it's content with ajax on tab switch.</description>
        </attribute>
        <attribute>
            <name>cache</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>When tab contents are lazy loaded by ajax toggleMode, caching only retrieves the tab contents once and subsequent toggles of a cached tab
			does not communicate with server. If caching is turned off, tab contents are refetched from server each time tab is clicked. This setting is true by default.
            </description>
        </attribute>
        <attribute>
            <name>collapsible</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>An active tab can be collapsed onclick when collapsible option is enabled</description>
        </attribute>
        <attribute>
            <name>event</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Event to use when selecting a tab</description>
        </attribute>
        <attribute>
            <name>tabChangeListener</name>
            <required>false</required>
            <type>javax.el.MethodExpression</type>
            <method-signature>void tabChangeListener(org.primefaces.event.TabChangeEvent)</method-signature>
            <description>Server side listener to invoke when a tab has changed.</description>
        </attribute>
        <attribute>
            <name>onTabChangeUpdate</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Component(s) to update after tabChangeListener is invoked.</description>
        </attribute>
        <attribute>
            <name>onTabChange</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to invoke when active tab changes.</description>
        </attribute>
        <attribute>
            <name>onTabShow</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description></description>
        </attribute>
        <attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Inline style of the main tabview container.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<description>Style class of the main tabview container.</description>
		</attribute>
    </attributes>
    <resources>
        <resource>
			<name>jquery/ui/jquery-ui.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>jquery/ui/jquery-ui.js</name>
		</resource>
        <resource>
            <name>core/core.js</name>
        </resource>
        <resource>
            <name>tabview/tabview.js</name>
        </resource>
    </resources>
</component>
